version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: todopostgres
    restart: always
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todo123
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./to-do-list
      dockerfile: Dockerfile
    container_name: todoapi
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: todouser
      SPRING_DATASOURCE_PASSWORD: todo123
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    build: 
      context: ./to-do-list-app
      dockerfile: Dockerfile
    container_name: todoweb
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
